import slugify from "@sindresorhus/slugify";

export const countries = [
    // missing from map
    { id: "cw", name: "Curaçao", visited: "2025" },
    { id: "vi", name: "Virgin Islands (U.S.)", visited: "2009, 2020" },
    { id: "vg", name: "Virgin Islands (British)", visited: "2009, 2025" },
    { id: "bm", name: "Bermuda", visited: "2013" },
    { id: "ky", name: "Cayman Islands", visited: "2017" },
    { id: "tc", name: "Turks and Caicos Islands", visited: "2019" },
    { id: "sx", name: "Sint Maarten (Dutch part)", visited: "2020" },
    { id: "mf", name: "Saint Martin (French part)", visited: "2020" },
    { id: "kn", name: "Saint Kitts and Nevis", visited: "2020" },
    { id: "dm", name: "Dominica", visited: "2020" },
    { id: "bb", name: "Barbados", visited: "2020" },
    // End missing

    { id: "ae", name: "United Arab Emirates" },
    { id: "af", name: "Afghanistan" },
    { id: "al", name: "Albania" },
    { id: "am", name: "Armenia" },
    { id: "ao", name: "Angola" },
    { id: "ar", name: "Argentina", visited: "2017" },
    { id: "at", name: "Austria", visited: "2004" },
    { id: "au", name: "Australia" },
    { id: "az", name: "Azerbaijan" },
    { id: "ba", name: "Bosnia and Herzegowina" },
    { id: "bd", name: "Bangladesh" },
    { id: "be", name: "Belgium" },
    { id: "bf", name: "Burkina Faso" },
    { id: "bg", name: "Bulgaria" },
    { id: "bi", name: "Burundi" },
    { id: "bj", name: "Benin" },
    { id: "bn", name: "Brunei" },
    { id: "bo", name: "Bolivia" },
    { id: "br", name: "Brazil" },
    { id: "bs", name: "Bahamas", visited: "2009, 2019, 2024" },
    { id: "bt", name: "Bhutan" },
    { id: "bw", name: "Botswana" },
    { id: "by", name: "Belarus" },
    { id: "bz", name: "Belize", visited: "2006, 2010, 2015" },
    { id: "ca", name: "Canada", visited: "2003, 2015, 2018" },
    { id: "cd", name: "Democratic Republic of the Congo" },
    { id: "cf", name: "Central African Republic" },
    { id: "cg", name: "Congo" },
    { id: "ch", name: "Switzerland" },
    { id: "ci", name: "Cote d'Ivoire" },
    { id: "cl", name: "Chile", visited: "2017" },
    { id: "cm", name: "Cameroon" },
    { id: "cn", name: "China" },
    { id: "co", name: "Colombia" },
    { id: "cr", name: "Costa Rica", visited: "2025" },
    { id: "cu", name: "Cuba" },
    { id: "cy", name: "Cyprus" },
    { id: "cz", name: "Czech" },
    { id: "de", name: "Germany", visited: "2004, 2012" },
    { id: "dj", name: "Djibouti" },
    { id: "dk", name: "Denmark", visited: "2012" },
    { id: "do", name: "Dominican Republic", visited: "2009, 2025" },
    { id: "dz", name: "Algeria" },
    { id: "ec", name: "Ecuador" },
    { id: "ee", name: "Estonia", visited: "2012" },
    { id: "eg", name: "Egypt" },
    { id: "eh", name: "West Sahara" },
    { id: "er", name: "Eritrea" },
    { id: "es", name: "Spain", visited: "2019 (Spain and Canary Islands)" },
    { id: "et", name: "Ethiopia" },
    { id: "fi", name: "Finland", visited: "2012" },
    { id: "fj", name: "Fiji" },
    { id: "fk", name: "Falkland Islands", visited: "201" },
    { id: "fr", name: "France" },
    { id: "ga", name: "Gabon" },
    { id: "gb", name: "United Kingdom", visited: "1996, 2001, 2011, 2012, 2019, 2024" },
    { id: "ge", name: "Georgia" },
    { id: "gh", name: "Ghana" },
    { id: "gl", name: "Greenland", visited: "2023" },
    { id: "gm", name: "Gambia" },
    { id: "gn", name: "Guinea" },
    { id: "gq", name: "Equatorial Guinea" },
    { id: "gr", name: "Greece", visited: "2022, 2024" },
    { id: "gt", name: "Guatemala", visited: "2025" },
    { id: "gw", name: "Guinea-Bissau" },
    { id: "gy", name: "Guyana" },
    { id: "hn", name: "Honduras", visited: "2015" },
    { id: "hr", name: "Croatia", visited: "2024" },
    { id: "ht", name: "Haiti" },
    { id: "hu", name: "Hungary" },
    { id: "id", name: "Indonesia" },
    { id: "ie", name: "Ireland" },
    { id: "il", name: "Israel" },
    { id: "in", name: "India" },
    { id: "iq", name: "Iraq" },
    { id: "ir", name: "Iran" },
    { id: "is", name: "Iceland", visited: "2023" },
    { id: "it", name: "Italy", visited: "1999, 2024" },
    { id: "jm", name: "Jamaica", visited: "2002, 2017" },
    { id: "jo", name: "Jordan" },
    { id: "jp", name: "Japan" },
    { id: "ke", name: "Kenya" },
    { id: "kg", name: "Kyrgyzstan" },
    { id: "kh", name: "Cambodia" },
    { id: "kp", name: "North Korea" },
    { id: "kr", name: "South Korea" },
    { id: "kw", name: "Kuwait" },
    { id: "kz", name: "Kazakhstan" },
    { id: "la", name: "Laos" },
    { id: "lb", name: "Lebanon" },
    { id: "lk", name: "Sri Lanka" },
    { id: "lr", name: "Liberia" },
    { id: "ls", name: "Lesotho" },
    { id: "lt", name: "Lithuania" },
    { id: "lu", name: "Luxembourg" },
    { id: "lv", name: "Latvia" },
    { id: "ly", name: "Libya" },
    { id: "ma", name: "Morocco", visited: "2019" },
    { id: "md", name: "Moldova" },
    { id: "me", name: "Montenegro", visited: "2024" },
    { id: "mg", name: "Madagascar" },
    { id: "mk", name: "Macedonia" },
    { id: "ml", name: "Mali" },
    { id: "mm", name: "Myanmar" },
    { id: "mn", name: "Mongolia" },
    { id: "mr", name: "Mauritania" },
    { id: "mw", name: "Malawi" },
    { id: "mx", name: "Mexico", visited: "2006, 2010, 2015, 2017, 2023, 2025" },
    { id: "my", name: "Malaysia" },
    { id: "mz", name: "Mozambique" },
    { id: "na", name: "Namibia" },
    { id: "nc", name: "New Caledonia" },
    { id: "ne", name: "Niger" },
    { id: "ng", name: "Nigeria" },
    { id: "ni", name: "Nicaragua" },
    { id: "nl", name: "Netherlands" },
    { id: "no", name: "Norway", visited: "2009, 2024" },
    { id: "np", name: "Nepal" },
    { id: "nz", name: "New Zealand" },
    { id: "om", name: "Oman" },
    { id: "pa", name: "Panama", visited: "2025" },
    { id: "pe", name: "Peru" },
    { id: "pg", name: "Papua New Guinea" },
    { id: "ph", name: "Philippines" },
    { id: "pk", name: "Pakistan" },
    { id: "pl", name: "Poland" },
    { id: "pr", name: "Puerto Rico", visited: "2020, 2025" },
    { id: "ps", name: "Palestine" },
    { id: "pt", name: "Portugal", visited: "2019 (Madeira), 2023 (Travis)" },
    { id: "py", name: "Paraguay" },
    { id: "qa", name: "Qatar" },
    { id: "ro", name: "Romania" },
    { id: "rs", name: "Serbia" },
    { id: "ru", name: "Russia", visited: "2012" },
    { id: "rw", name: "Rwanda" },
    { id: "sa", name: "Saudi Arabia" },
    { id: "sb", name: "Solomon Islands" },
    { id: "sd", name: "Sudan" },
    { id: "se", name: "Sweden", visited: "2012" },
    { id: "sg", name: "Singapore" },
    { id: "si", name: "Slovenia", visited: "2024" },
    { id: "sk", name: "Slovakia" },
    { id: "sl", name: "Sierra Leone" },
    { id: "sn", name: "Senegal" },
    { id: "so", name: "Somalia" },
    { id: "sr", name: "Suriname" },
    { id: "ss", name: "South Sudan" },
    { id: "sv", name: "El Salvador" },
    { id: "sy", name: "Syria" },
    { id: "sz", name: "Swaziland" },
    { id: "td", name: "Chad" },
    { id: "tf", name: "Fr. S. Antarctic Lands" },
    { id: "tg", name: "Togo" },
    { id: "th", name: "Thailand" },
    { id: "tj", name: "Tajikistan" },
    { id: "tl", name: "Timor-Leste" },
    { id: "tm", name: "Turkmenistan" },
    { id: "tn", name: "Tunisia" },
    { id: "tr", name: "Turkey", visited: "2022" },
    { id: "tt", name: "Trinidad and Tobago" },
    { id: "tw", name: "Taiwan" },
    { id: "tz", name: "Tanzania" },
    { id: "ua", name: "Ukraine" },
    { id: "ug", name: "Uganda" },
    { id: "us", name: "United States", visited: "all the time" },
    { id: "uy", name: "Uruguay", visited: "2017" },
    { id: "uz", name: "Uzbekistan" },
    { id: "ve", name: "Venezuela" },
    { id: "vn", name: "Vietnam" },
    { id: "vu", name: "Vanuatu" },
    { id: "ye", name: "Yemen" },
    { id: "za", name: "South Africa" },
    { id: "zm", name: "Zambia" },
    { id: "zw", name: "Zimbabwe" }
];

export const byId = {};

for (const v of countries) {
    if (!v.tag) {
        v.tag = slugify(v.name, {decamelize: false});
    }
    byId[v.id] = v;
}